package development;
import javax.swing.GroupLayout.Alignment;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

public class addEditUsers extends javax.swing.JFrame {

    /**
     * Creates new form addEditUsers
     */
    public addEditUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        fnamefield = new javax.swing.JTextField();
        lnamefield = new javax.swing.JTextField();
        idfield = new javax.swing.JTextField();
        fnamelabel = new javax.swing.JLabel();
        lnamelabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        poslabel = new javax.swing.JLabel();
        positions = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        importbtn = new javax.swing.JButton();
        
        

        setLocationRelativeTo(null);
        setTitle("Add/Edit Users");
        
        DefaultTableModel model=new DefaultTableModel();
        String nextRowId = Integer.toString(model.getRowCount());
        
        
        
        scrollPane.setViewportView(table);

        fnamelabel.setText("First Name");

        lnamelabel.setText("Last Name");

        idlabel.setText("ID Number");

        poslabel.setText("Position");

        positions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Manager", "Moderator", "Index User", "Warehouse Operator" }));
        
        //YOU FUCKED UP
        addbtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		final String fname;
        		if(e.getSource()==addbtn) {
        			
        			//DOESNT WORK, FIX IT CUNT
        	        table.setModel(new javax.swing.table.DefaultTableModel(
        	            new Object [][] {
        	                {fname, null, null, null},
        	                {null, null, null, null},
        	                {null, null, null, null},
        	                {null, null, null, null}
        	            },
        	            new String [] {
        	                "","First Name", "Last Name", "ID No", "Position"
        	            }
        	        ));
        			/*model.addRow(new Object[][] {
        	        		nextRowId, fnamefield.getText(),
        	        		lnamefield.getText(), idfield.getText(),
        	        		(String)positions.getSelectedItem()
        	        });*/
        		}
        	}
        });
        addbtn.setText("Add");

        
        //DO NOT DELETE THIS
        
        editbtn.addActionListener(new ActionListener(){
        	public void actionPerformed(ActionEvent e) {
        		if(e.getSource()==editbtn) {
        			//WORK ON THIS
        			//model.getSelecteditem();
        			positions.setEditable(true);
        		}
        	}
        });
        editbtn.setText("Edit");
        
        deletebtn.setText("Delete");

        importbtn.setText("Import");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(poslabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGap(17)
        					.addComponent(positions, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(idlabel, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(idfield, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(fnamelabel)
        						.addComponent(lnamelabel))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lnamefield, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        						.addComponent(fnamefield, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(addbtn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(deletebtn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(16)
        							.addComponent(importbtn))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(18)
        							.addComponent(editbtn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 452, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(19, Short.MAX_VALUE)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addGap(56)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(fnamelabel)
        				.addComponent(fnamefield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lnamelabel)
        				.addComponent(lnamefield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(idlabel)
        				.addComponent(idfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(poslabel)
        				.addComponent(positions, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(addbtn)
        				.addComponent(editbtn))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(deletebtn)
        				.addComponent(importbtn))
        			.addContainerGap(73, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JTextField fnamefield;
    private javax.swing.JLabel fnamelabel;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel idlabel;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton importbtn;
    private javax.swing.JTextField lnamefield;
    private javax.swing.JLabel lnamelabel;
    private javax.swing.JComboBox<String> positions;
    private javax.swing.JLabel poslabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration                   
}
